[LINE:818] # INFO [2019-09-27 03:15:51,497]: Starting on server 2.1
[LINE:735] # INFO [2019-09-27 03:15:51,508]: Starting new HTTPS connection (1): api.telegram.org
[LINE:649] # INFO [2019-09-27 03:15:59,913]: Petr Volnov üëé
[LINE:735] # INFO [2019-09-27 03:15:59,918]: Starting new HTTPS connection (1): api.telegram.org
[LINE:649] # INFO [2019-09-27 03:16:04,542]: Petr Volnov üëÅ
[LINE:649] # INFO [2019-09-27 03:16:13,145]: Petr Volnov üí©
[LINE:735] # INFO [2019-09-27 03:16:13,152]: Starting new HTTPS connection (1): api.telegram.org
[LINE:649] # INFO [2019-09-27 03:16:45,546]: Daniel Patrik üëÅ
[LINE:649] # INFO [2019-09-27 03:16:49,935]: Daniel Patrik –ü–æ–¥–æ–±—Ä–∞—Ç—å —Ñ–∏–ª—å–ºüéû
[LINE:649] # INFO [2019-09-27 03:16:52,035]: Daniel Patrik üëé
[LINE:649] # INFO [2019-09-27 03:17:43,486]: Daniel Patrik üëé
[LINE:649] # INFO [2019-09-27 03:18:33,015]: Daniel Patrik üëé
[LINE:649] # INFO [2019-09-27 03:18:40,417]: Daniel Patrik üëé
[LINE:649] # INFO [2019-09-27 03:18:47,447]: Daniel Patrik üëé
[LINE:649] # INFO [2019-09-27 03:18:51,888]: Daniel Patrik üëç
[LINE:434] # INFO [2019-09-27 03:19:05,893]: the0smith: youtube_3423
[LINE:735] # INFO [2019-09-27 03:19:05,905]: Starting new HTTPS connection (1): www.youtube.com
[LINE:434] # INFO [2019-09-27 03:19:34,875]: the0smith: error_3423_delete
[LINE:434] # INFO [2019-09-27 03:19:39,702]: the0smith: youtube_3423
[LINE:735] # INFO [2019-09-27 03:19:39,713]: Starting new HTTPS connection (1): www.youtube.com
[LINE:434] # INFO [2019-09-27 03:19:53,705]: the0smith: error_3423_delete
[LINE:649] # INFO [2019-09-27 03:19:56,239]: Daniel Patrik üí©
[LINE:649] # INFO [2019-09-27 03:21:00,364]: Daniel Patrik üëé
[LINE:649] # INFO [2019-09-27 03:24:00,058]: Daniel Patrik üëÅ
[LINE:434] # INFO [2019-09-27 03:24:22,128]: the0smith: more_9976
[LINE:649] # INFO [2019-09-27 03:24:27,976]: Daniel Patrik üëç
[LINE:434] # INFO [2019-09-27 03:24:36,102]: the0smith: more_1503
[LINE:465] # ERROR [2019-09-27 03:24:36,209]: Can't edit filmA request to the Telegram API was unsuccessful. The server returned HTTP 400 Bad Request. Response body:
[b'{"ok":false,"error_code":400,"description":"Bad Request: can\'t parse entities: Can\'t find end tag corresponding to start tag at byte offset 1716"}']
[LINE:649] # INFO [2019-09-27 03:25:15,456]: Daniel Patrik üëé
[LINE:434] # INFO [2019-09-27 03:25:20,004]: the0smith: more_225975
[LINE:649] # INFO [2019-09-27 03:25:44,932]: Daniel Patrik üëé
[LINE:649] # INFO [2019-09-27 03:26:12,056]: Daniel Patrik üëé
[LINE:434] # INFO [2019-09-27 03:26:16,889]: the0smith: more_6836
[LINE:649] # INFO [2019-09-27 03:26:52,209]: Daniel Patrik üëé
[LINE:263] # INFO [2019-09-27 03:26:52,845]: Predicting: 0:00:00.054233
[LINE:649] # INFO [2019-09-27 03:27:17,433]: Daniel Patrik üëç
[LINE:649] # INFO [2019-09-27 03:27:28,516]: Daniel Patrik –ü–æ–Ω—Ä–∞–≤–∏–≤—à–∏–µ—Å—èüß°
[LINE:434] # INFO [2019-09-27 03:27:31,889]: the0smith: film_2134
[LINE:434] # INFO [2019-09-27 03:27:34,309]: the0smith: showed_2134
[LINE:434] # INFO [2019-09-27 03:27:36,043]: the0smith: addstars_2134_9
[LINE:649] # INFO [2019-09-27 03:29:07,104]: Petr Volnov üëÅ
[LINE:821] # INFO [2019-09-27 03:30:12,596]: Starting on server 2.1
[LINE:735] # INFO [2019-09-27 03:30:12,608]: Starting new HTTPS connection (1): api.telegram.org
[LINE:238] # INFO [2019-09-27 04:03:46,768]: Resetting dropped connection: api.telegram.org
[LINE:735] # INFO [2019-09-27 04:19:05,062]: Starting new HTTPS connection (1): api.telegram.org
[LINE:74] # INFO [2019-09-27 04:19:05,663]: New user @None
[LINE:735] # INFO [2019-09-27 04:19:05,667]: Starting new HTTPS connection (1): alarmerbot.ru
[LINE:74] # INFO [2019-09-27 04:19:17,535]: New user @None
[LINE:735] # INFO [2019-09-27 04:19:17,537]: Starting new HTTPS connection (1): alarmerbot.ru
[LINE:436] # INFO [2019-09-27 04:19:18,959]: None: info_sex_0
[LINE:735] # INFO [2019-09-27 04:19:18,981]: Starting new HTTPS connection (1): api.telegram.org
[LINE:436] # INFO [2019-09-27 04:19:20,437]: None: info_sex_0
[LINE:652] # INFO [2019-09-27 04:19:25,057]: Daniil Orekhov 37
[LINE:652] # INFO [2019-09-27 04:19:26,867]: –î–µ–Ω–∏—Å –Ø–∫–æ–≤–ª–µ–≤ 30
[LINE:652] # INFO [2019-09-27 04:19:31,246]: Daniil Orekhov –ü–æ–¥–æ–±—Ä–∞—Ç—å —Ñ–∏–ª—å–ºüéû
[LINE:265] # INFO [2019-09-27 04:19:31,583]: Predicting: 0:00:00.076120
[LINE:652] # INFO [2019-09-27 04:19:33,116]: –î–µ–Ω–∏—Å –Ø–∫–æ–≤–ª–µ–≤ –ü–æ–¥–æ–±—Ä–∞—Ç—å —Ñ–∏–ª—å–ºüéû
[LINE:265] # INFO [2019-09-27 04:19:33,320]: Predicting: 0:00:00.053115
[LINE:74] # INFO [2019-09-27 04:19:33,385]: New user @None
[LINE:735] # INFO [2019-09-27 04:19:33,387]: Starting new HTTPS connection (1): alarmerbot.ru
[LINE:436] # INFO [2019-09-27 04:19:39,096]: None: info_sex_0
[LINE:347] # INFO [2019-09-27 04:19:41,290]: like like_-1
[LINE:347] # INFO [2019-09-27 04:19:41,294]: like like_-1
[LINE:265] # INFO [2019-09-27 04:19:41,381]: Predicting: 0:00:00.060362
[LINE:265] # INFO [2019-09-27 04:19:41,386]: Predicting: 0:00:00.067141
[LINE:162] # INFO [2019-09-27 04:19:41,487]: Cant edit list of films
[LINE:162] # INFO [2019-09-27 04:19:41,490]: Cant edit list of films
[LINE:265] # INFO [2019-09-27 04:19:41,694]: Predicting: 0:00:00.062368
[LINE:265] # INFO [2019-09-27 04:19:41,698]: Predicting: 0:00:00.060832
[LINE:162] # INFO [2019-09-27 04:19:41,799]: Cant edit list of films
[LINE:162] # INFO [2019-09-27 04:19:41,808]: Cant edit list of films
[LINE:265] # INFO [2019-09-27 04:19:41,998]: Predicting: 0:00:00.067915
[LINE:265] # INFO [2019-09-27 04:19:42,004]: Predicting: 0:00:00.064927
[LINE:162] # INFO [2019-09-27 04:19:42,112]: Cant edit list of films
[LINE:162] # INFO [2019-09-27 04:19:42,116]: Cant edit list of films
[LINE:265] # INFO [2019-09-27 04:19:42,345]: Predicting: 0:00:00.069462
[LINE:265] # INFO [2019-09-27 04:19:42,350]: Predicting: 0:00:00.071677
[LINE:162] # INFO [2019-09-27 04:19:42,458]: Cant edit list of films
[LINE:265] # INFO [2019-09-27 04:19:42,520]: Predicting: 0:00:00.033901
[LINE:265] # INFO [2019-09-27 04:19:42,622]: Predicting: 0:00:00.032575
[LINE:162] # INFO [2019-09-27 04:19:42,730]: Cant edit list of films
[LINE:652] # INFO [2019-09-27 04:19:45,420]: –ê—Ä—Ç–µ–º None 40
[LINE:347] # INFO [2019-09-27 04:19:47,679]: like like_-1
[LINE:65] # ERROR [2019-09-27 04:19:47,742]: ValueError occurred, args=("'a' cannot be empty unless no samples are taken",)
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/telebot/util.py", line 59, in run
    task(*args, **kwargs)
  File "telsent.py", line 376, in likefilm
    u = next_films_collections(u)
  File "telsent.py", line 304, in next_films_collections
    u.predict_films += predict_film_list(u.tel_id)
  File "telsent.py", line 263, in predict_film_list
    pred = np.random.choice(list(predict.keys()), p=pb, size=20)
  File "mtrand.pyx", line 773, in numpy.random.mtrand.RandomState.choice
ValueError: 'a' cannot be empty unless no samples are taken

[LINE:831] # INFO [2019-09-27 04:19:47,742]: 'a' cannot be empty unless no samples are taken
[LINE:836] # INFO [2019-09-27 04:19:47,744]: <traceback object at 0x7f48260b1f08>
[LINE:74] # INFO [2019-09-27 04:19:47,744]: 'a' cannot be empty unless no samples are taken
[LINE:735] # INFO [2019-09-27 04:19:47,745]: Starting new HTTPS connection (1): alarmerbot.ru
[LINE:831] # INFO [2019-09-27 04:19:48,156]: 'a' cannot be empty unless no samples are taken
[LINE:836] # INFO [2019-09-27 04:19:48,158]: <traceback object at 0x7f48260b1808>
[LINE:74] # INFO [2019-09-27 04:19:48,159]: 'a' cannot be empty unless no samples are taken
[LINE:735] # INFO [2019-09-27 04:19:48,161]: Starting new HTTPS connection (1): alarmerbot.ru
[LINE:735] # INFO [2019-09-27 04:19:48,163]: Starting new HTTPS connection (1): api.telegram.org
[LINE:65] # ERROR [2019-09-27 04:19:48,552]: ApiException occurred, args=('A request to the Telegram API was unsuccessful. The server returned HTTP 409 Conflict. Response body:\n[b\'{"ok":false,"error_code":409,"description":"Conflict: terminated by other getUpdates request; make sure that only one bot instance is running"}\']',)
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/telebot/util.py", line 59, in run
    task(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/telebot/__init__.py", line 276, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1), timeout=timeout)
  File "/usr/local/lib/python3.5/dist-packages/telebot/__init__.py", line 246, in get_updates
    json_updates = apihelper.get_updates(self.token, offset, limit, timeout, allowed_updates)
  File "/usr/local/lib/python3.5/dist-packages/telebot/apihelper.py", line 180, in get_updates
    return _make_request(token, method_url, params=payload)
  File "/usr/local/lib/python3.5/dist-packages/telebot/apihelper.py", line 56, in _make_request
    return _check_result(method_name, result)['result']
  File "/usr/local/lib/python3.5/dist-packages/telebot/apihelper.py", line 75, in _check_result
    raise ApiException(msg, method_name, result)
telebot.apihelper.ApiException: A request to the Telegram API was unsuccessful. The server returned HTTP 409 Conflict. Response body:
[b'{"ok":false,"error_code":409,"description":"Conflict: terminated by other getUpdates request; make sure that only one bot instance is running"}']

[LINE:831] # INFO [2019-09-27 04:19:48,591]: 'a' cannot be empty unless no samples are taken
[LINE:836] # INFO [2019-09-27 04:19:48,592]: <traceback object at 0x7f48260b1f08>
[LINE:74] # INFO [2019-09-27 04:19:48,592]: 'a' cannot be empty unless no samples are taken
[LINE:735] # INFO [2019-09-27 04:19:48,595]: Starting new HTTPS connection (1): alarmerbot.ru
[LINE:735] # INFO [2019-09-27 04:19:48,597]: Starting new HTTPS connection (1): api.telegram.org
[LINE:831] # INFO [2019-09-27 04:19:49,032]: 'a' cannot be empty unless no samples are taken
[LINE:836] # INFO [2019-09-27 04:19:49,034]: <traceback object at 0x7f48260b1808>
[LINE:74] # INFO [2019-09-27 04:19:49,035]: 'a' cannot be empty unless no samples are taken
[LINE:735] # INFO [2019-09-27 04:19:49,037]: Starting new HTTPS connection (1): alarmerbot.ru
[LINE:735] # INFO [2019-09-27 04:19:49,039]: Starting new HTTPS connection (1): api.telegram.org
[LINE:831] # INFO [2019-09-27 04:19:49,471]: 'a' cannot be empty unless no samples are taken
[LINE:836] # INFO [2019-09-27 04:19:49,472]: <traceback object at 0x7f48260b1f08>
[LINE:74] # INFO [2019-09-27 04:19:49,473]: 'a' cannot be empty unless no samples are taken
[LINE:735] # INFO [2019-09-27 04:19:49,475]: Starting new HTTPS connection (1): alarmerbot.ru
[LINE:735] # INFO [2019-09-27 04:19:49,477]: Starting new HTTPS connection (1): api.telegram.org
[LINE:821] # INFO [2019-09-27 04:44:07,217]: Starting on server 2.1
[LINE:735] # INFO [2019-09-27 04:44:07,227]: Starting new HTTPS connection (1): api.telegram.org
[LINE:652] # INFO [2019-09-27 04:44:07,674]: –ê—Ä—Ç–µ–º None –ü–æ–¥–æ–±—Ä–∞—Ç—å —Ñ–∏–ª—å–ºüéû
[LINE:735] # INFO [2019-09-27 04:44:07,676]: Starting new HTTPS connection (1): api.telegram.org
[LINE:652] # INFO [2019-09-27 04:44:07,685]: –ê—Ä—Ç–µ–º None –ü–æ–Ω—Ä–∞–≤–∏–≤—à–∏–µ—Å—èüß°
[LINE:735] # INFO [2019-09-27 04:44:07,688]: Starting new HTTPS connection (1): api.telegram.org
[LINE:74] # INFO [2019-09-27 04:44:08,290]: New user @None
[LINE:735] # INFO [2019-09-27 04:44:08,291]: Starting new HTTPS connection (1): alarmerbot.ru
[LINE:265] # INFO [2019-09-27 04:44:08,327]: Predicting: 0:00:00.079292
[LINE:652] # INFO [2019-09-27 04:44:08,466]: Daniil Orekhov /
[LINE:65] # ERROR [2019-09-27 04:44:08,976]: ApiException occurred, args=('A request to the Telegram API was unsuccessful. The server returned HTTP 403 Forbidden. Response body:\n[b\'{"ok":false,"error_code":403,"description":"Forbidden: bot was blocked by the user"}\']',)
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/telebot/util.py", line 59, in run
    task(*args, **kwargs)
  File "telsent.py", line 327, in startf
    bot.send_message(message.chat.id, START_PROFIL_TEXT, reply_markup=markup)
  File "/usr/local/lib/python3.5/dist-packages/telebot/__init__.py", line 598, in send_message
    reply_markup, parse_mode, disable_notification))
  File "/usr/local/lib/python3.5/dist-packages/telebot/apihelper.py", line 140, in send_message
    return _make_request(token, method_url, params=payload, method='post')
  File "/usr/local/lib/python3.5/dist-packages/telebot/apihelper.py", line 56, in _make_request
    return _check_result(method_name, result)['result']
  File "/usr/local/lib/python3.5/dist-packages/telebot/apihelper.py", line 75, in _check_result
    raise ApiException(msg, method_name, result)
telebot.apihelper.ApiException: A request to the Telegram API was unsuccessful. The server returned HTTP 403 Forbidden. Response body:
[b'{"ok":false,"error_code":403,"description":"Forbidden: bot was blocked by the user"}']

[LINE:417] # ERROR [2019-09-27 04:44:08,984]: A request to the Telegram API was unsuccessful. The server returned HTTP 403 Forbidden. Response body:
[b'{"ok":false,"error_code":403,"description":"Forbidden: bot was blocked by the user"}']
[LINE:65] # ERROR [2019-09-27 04:44:08,986]: ApiException occurred, args=('A request to the Telegram API was unsuccessful. The server returned HTTP 403 Forbidden. Response body:\n[b\'{"ok":false,"error_code":403,"description":"Forbidden: bot was blocked by the user"}\']',)
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/telebot/util.py", line 59, in run
    task(*args, **kwargs)
  File "telsent.py", line 331, in startf
    bot.send_message(message.chat.id, YOU_THERE_TEXT)
  File "/usr/local/lib/python3.5/dist-packages/telebot/__init__.py", line 598, in send_message
    reply_markup, parse_mode, disable_notification))
  File "/usr/local/lib/python3.5/dist-packages/telebot/apihelper.py", line 140, in send_message
    return _make_request(token, method_url, params=payload, method='post')
  File "/usr/local/lib/python3.5/dist-packages/telebot/apihelper.py", line 56, in _make_request
    return _check_result(method_name, result)['result']
  File "/usr/local/lib/python3.5/dist-packages/telebot/apihelper.py", line 75, in _check_result
    raise ApiException(msg, method_name, result)
telebot.apihelper.ApiException: A request to the Telegram API was unsuccessful. The server returned HTTP 403 Forbidden. Response body:
[b'{"ok":false,"error_code":403,"description":"Forbidden: bot was blocked by the user"}']

[LINE:652] # INFO [2019-09-27 04:44:08,990]: Kirill None —Ñ–∏–ª—å–º
[LINE:65] # ERROR [2019-09-27 04:44:09,103]: ApiException occurred, args=('A request to the Telegram API was unsuccessful. The server returned HTTP 403 Forbidden. Response body:\n[b\'{"ok":false,"error_code":403,"description":"Forbidden: bot was blocked by the user"}\']',)
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/telebot/util.py", line 59, in run
    task(*args, **kwargs)
  File "telsent.py", line 331, in startf
    bot.send_message(message.chat.id, YOU_THERE_TEXT)
  File "/usr/local/lib/python3.5/dist-packages/telebot/__init__.py", line 598, in send_message
    reply_markup, parse_mode, disable_notification))
  File "/usr/local/lib/python3.5/dist-packages/telebot/apihelper.py", line 140, in send_message
    return _make_request(token, method_url, params=payload, method='post')
  File "/usr/local/lib/python3.5/dist-packages/telebot/apihelper.py", line 56, in _make_request
    return _check_result(method_name, result)['result']
  File "/usr/local/lib/python3.5/dist-packages/telebot/apihelper.py", line 75, in _check_result
    raise ApiException(msg, method_name, result)
telebot.apihelper.ApiException: A request to the Telegram API was unsuccessful. The server returned HTTP 403 Forbidden. Response body:
[b'{"ok":false,"error_code":403,"description":"Forbidden: bot was blocked by the user"}']

[LINE:65] # ERROR [2019-09-27 04:44:09,133]: ApiException occurred, args=('A request to the Telegram API was unsuccessful. The server returned HTTP 403 Forbidden. Response body:\n[b\'{"ok":false,"error_code":403,"description":"Forbidden: bot was blocked by the user"}\']',)
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/telebot/util.py", line 59, in run
    task(*args, **kwargs)
  File "telsent.py", line 664, in repeat_all_messages
    bot.send_message(message.chat.id, START_BAD_PASS_TEXT)
  File "/usr/local/lib/python3.5/dist-packages/telebot/__init__.py", line 598, in send_message
    reply_markup, parse_mode, disable_notification))
  File "/usr/local/lib/python3.5/dist-packages/telebot/apihelper.py", line 140, in send_message
    return _make_request(token, method_url, params=payload, method='post')
  File "/usr/local/lib/python3.5/dist-packages/telebot/apihelper.py", line 56, in _make_request
    return _check_result(method_name, result)['result']
  File "/usr/local/lib/python3.5/dist-packages/telebot/apihelper.py", line 75, in _check_result
    raise ApiException(msg, method_name, result)
telebot.apihelper.ApiException: A request to the Telegram API was unsuccessful. The server returned HTTP 403 Forbidden. Response body:
[b'{"ok":false,"error_code":403,"description":"Forbidden: bot was blocked by the user"}']

[LINE:65] # ERROR [2019-09-27 04:44:09,259]: ApiException occurred, args=('A request to the Telegram API was unsuccessful. The server returned HTTP 403 Forbidden. Response body:\n[b\'{"ok":false,"error_code":403,"description":"Forbidden: bot was blocked by the user"}\']',)
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/telebot/util.py", line 59, in run
    task(*args, **kwargs)
  File "telsent.py", line 331, in startf
    bot.send_message(message.chat.id, YOU_THERE_TEXT)
  File "/usr/local/lib/python3.5/dist-packages/telebot/__init__.py", line 598, in send_message
    reply_markup, parse_mode, disable_notification))
  File "/usr/local/lib/python3.5/dist-packages/telebot/apihelper.py", line 140, in send_message
    return _make_request(token, method_url, params=payload, method='post')
  File "/usr/local/lib/python3.5/dist-packages/telebot/apihelper.py", line 56, in _make_request
    return _check_result(method_name, result)['result']
  File "/usr/local/lib/python3.5/dist-packages/telebot/apihelper.py", line 75, in _check_result
    raise ApiException(msg, method_name, result)
telebot.apihelper.ApiException: A request to the Telegram API was unsuccessful. The server returned HTTP 403 Forbidden. Response body:
[b'{"ok":false,"error_code":403,"description":"Forbidden: bot was blocked by the user"}']

[LINE:417] # ERROR [2019-09-27 04:44:09,263]: A request to the Telegram API was unsuccessful. The server returned HTTP 403 Forbidden. Response body:
[b'{"ok":false,"error_code":403,"description":"Forbidden: bot was blocked by the user"}']
[LINE:652] # INFO [2019-09-27 04:44:09,268]: Kirill None –∫ –∑–≤–µ–∑–¥–∞–º
[LINE:65] # ERROR [2019-09-27 04:44:09,369]: ApiException occurred, args=('A request to the Telegram API was unsuccessful. The server returned HTTP 403 Forbidden. Response body:\n[b\'{"ok":false,"error_code":403,"description":"Forbidden: bot was blocked by the user"}\']',)
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/telebot/util.py", line 59, in run
    task(*args, **kwargs)
  File "telsent.py", line 331, in startf
    bot.send_message(message.chat.id, YOU_THERE_TEXT)
  File "/usr/local/lib/python3.5/dist-packages/telebot/__init__.py", line 598, in send_message
    reply_markup, parse_mode, disable_notification))
  File "/usr/local/lib/python3.5/dist-packages/telebot/apihelper.py", line 140, in send_message
    return _make_request(token, method_url, params=payload, method='post')
  File "/usr/local/lib/python3.5/dist-packages/telebot/apihelper.py", line 56, in _make_request
    return _check_result(method_name, result)['result']
  File "/usr/local/lib/python3.5/dist-packages/telebot/apihelper.py", line 75, in _check_result
    raise ApiException(msg, method_name, result)
telebot.apihelper.ApiException: A request to the Telegram API was unsuccessful. The server returned HTTP 403 Forbidden. Response body:
[b'{"ok":false,"error_code":403,"description":"Forbidden: bot was blocked by the user"}']

[LINE:65] # ERROR [2019-09-27 04:44:09,385]: ApiException occurred, args=('A request to the Telegram API was unsuccessful. The server returned HTTP 403 Forbidden. Response body:\n[b\'{"ok":false,"error_code":403,"description":"Forbidden: bot was blocked by the user"}\']',)
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/telebot/util.py", line 59, in run
    task(*args, **kwargs)
  File "telsent.py", line 664, in repeat_all_messages
    bot.send_message(message.chat.id, START_BAD_PASS_TEXT)
  File "/usr/local/lib/python3.5/dist-packages/telebot/__init__.py", line 598, in send_message
    reply_markup, parse_mode, disable_notification))
  File "/usr/local/lib/python3.5/dist-packages/telebot/apihelper.py", line 140, in send_message
    return _make_request(token, method_url, params=payload, method='post')
  File "/usr/local/lib/python3.5/dist-packages/telebot/apihelper.py", line 56, in _make_request
    return _check_result(method_name, result)['result']
  File "/usr/local/lib/python3.5/dist-packages/telebot/apihelper.py", line 75, in _check_result
    raise ApiException(msg, method_name, result)
telebot.apihelper.ApiException: A request to the Telegram API was unsuccessful. The server returned HTTP 403 Forbidden. Response body:
[b'{"ok":false,"error_code":403,"description":"Forbidden: bot was blocked by the user"}']

[LINE:652] # INFO [2019-09-27 04:44:09,389]: Kirill None –Ω–∞–π—Ç–∏ —Ñ–∏–ª—å–º
[LINE:65] # ERROR [2019-09-27 04:44:09,507]: ApiException occurred, args=('A request to the Telegram API was unsuccessful. The server returned HTTP 403 Forbidden. Response body:\n[b\'{"ok":false,"error_code":403,"description":"Forbidden: bot was blocked by the user"}\']',)
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/telebot/util.py", line 59, in run
    task(*args, **kwargs)
  File "telsent.py", line 664, in repeat_all_messages
    bot.send_message(message.chat.id, START_BAD_PASS_TEXT)
  File "/usr/local/lib/python3.5/dist-packages/telebot/__init__.py", line 598, in send_message
    reply_markup, parse_mode, disable_notification))
  File "/usr/local/lib/python3.5/dist-packages/telebot/apihelper.py", line 140, in send_message
    return _make_request(token, method_url, params=payload, method='post')
  File "/usr/local/lib/python3.5/dist-packages/telebot/apihelper.py", line 56, in _make_request
    return _check_result(method_name, result)['result']
  File "/usr/local/lib/python3.5/dist-packages/telebot/apihelper.py", line 75, in _check_result
    raise ApiException(msg, method_name, result)
telebot.apihelper.ApiException: A request to the Telegram API was unsuccessful. The server returned HTTP 403 Forbidden. Response body:
[b'{"ok":false,"error_code":403,"description":"Forbidden: bot was blocked by the user"}']

[LINE:65] # ERROR [2019-09-27 04:44:09,618]: ApiException occurred, args=('A request to the Telegram API was unsuccessful. The server returned HTTP 403 Forbidden. Response body:\n[b\'{"ok":false,"error_code":403,"description":"Forbidden: bot was blocked by the user"}\']',)
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/telebot/util.py", line 59, in run
    task(*args, **kwargs)
  File "telsent.py", line 331, in startf
    bot.send_message(message.chat.id, YOU_THERE_TEXT)
  File "/usr/local/lib/python3.5/dist-packages/telebot/__init__.py", line 598, in send_message
    reply_markup, parse_mode, disable_notification))
  File "/usr/local/lib/python3.5/dist-packages/telebot/apihelper.py", line 140, in send_message
    return _make_request(token, method_url, params=payload, method='post')
  File "/usr/local/lib/python3.5/dist-packages/telebot/apihelper.py", line 56, in _make_request
    return _check_result(method_name, result)['result']
  File "/usr/local/lib/python3.5/dist-packages/telebot/apihelper.py", line 75, in _check_result
    raise ApiException(msg, method_name, result)
telebot.apihelper.ApiException: A request to the Telegram API was unsuccessful. The server returned HTTP 403 Forbidden. Response body:
[b'{"ok":false,"error_code":403,"description":"Forbidden: bot was blocked by the user"}']

[LINE:65] # ERROR [2019-09-27 04:44:09,639]: ApiException occurred, args=('A request to the Telegram API was unsuccessful. The server returned HTTP 403 Forbidden. Response body:\n[b\'{"ok":false,"error_code":403,"description":"Forbidden: bot was blocked by the user"}\']',)
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/telebot/util.py", line 59, in run
    task(*args, **kwargs)
  File "telsent.py", line 331, in startf
    bot.send_message(message.chat.id, YOU_THERE_TEXT)
  File "/usr/local/lib/python3.5/dist-packages/telebot/__init__.py", line 598, in send_message
    reply_markup, parse_mode, disable_notification))
  File "/usr/local/lib/python3.5/dist-packages/telebot/apihelper.py", line 140, in send_message
    return _make_request(token, method_url, params=payload, method='post')
  File "/usr/local/lib/python3.5/dist-packages/telebot/apihelper.py", line 56, in _make_request
    return _check_result(method_name, result)['result']
  File "/usr/local/lib/python3.5/dist-packages/telebot/apihelper.py", line 75, in _check_result
    raise ApiException(msg, method_name, result)
telebot.apihelper.ApiException: A request to the Telegram API was unsuccessful. The server returned HTTP 403 Forbidden. Response body:
[b'{"ok":false,"error_code":403,"description":"Forbidden: bot was blocked by the user"}']

[LINE:652] # INFO [2019-09-27 04:44:09,646]: Kirill None /—Ñ–∏–ª—å–º
[LINE:65] # ERROR [2019-09-27 04:44:09,736]: ApiException occurred, args=('A request to the Telegram API was unsuccessful. The server returned HTTP 403 Forbidden. Response body:\n[b\'{"ok":false,"error_code":403,"description":"Forbidden: bot was blocked by the user"}\']',)
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/telebot/util.py", line 59, in run
    task(*args, **kwargs)
  File "telsent.py", line 331, in startf
    bot.send_message(message.chat.id, YOU_THERE_TEXT)
  File "/usr/local/lib/python3.5/dist-packages/telebot/__init__.py", line 598, in send_message
    reply_markup, parse_mode, disable_notification))
  File "/usr/local/lib/python3.5/dist-packages/telebot/apihelper.py", line 140, in send_message
    return _make_request(token, method_url, params=payload, method='post')
  File "/usr/local/lib/python3.5/dist-packages/telebot/apihelper.py", line 56, in _make_request
    return _check_result(method_name, result)['result']
  File "/usr/local/lib/python3.5/dist-packages/telebot/apihelper.py", line 75, in _check_result
    raise ApiException(msg, method_name, result)
telebot.apihelper.ApiException: A request to the Telegram API was unsuccessful. The server returned HTTP 403 Forbidden. Response body:
[b'{"ok":false,"error_code":403,"description":"Forbidden: bot was blocked by the user"}']

[LINE:65] # ERROR [2019-09-27 04:44:09,771]: ApiException occurred, args=('A request to the Telegram API was unsuccessful. The server returned HTTP 403 Forbidden. Response body:\n[b\'{"ok":false,"error_code":403,"description":"Forbidden: bot was blocked by the user"}\']',)
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/telebot/util.py", line 59, in run
    task(*args, **kwargs)
  File "telsent.py", line 664, in repeat_all_messages
    bot.send_message(message.chat.id, START_BAD_PASS_TEXT)
  File "/usr/local/lib/python3.5/dist-packages/telebot/__init__.py", line 598, in send_message
    reply_markup, parse_mode, disable_notification))
  File "/usr/local/lib/python3.5/dist-packages/telebot/apihelper.py", line 140, in send_message
    return _make_request(token, method_url, params=payload, method='post')
  File "/usr/local/lib/python3.5/dist-packages/telebot/apihelper.py", line 56, in _make_request
    return _check_result(method_name, result)['result']
  File "/usr/local/lib/python3.5/dist-packages/telebot/apihelper.py", line 75, in _check_result
    raise ApiException(msg, method_name, result)
telebot.apihelper.ApiException: A request to the Telegram API was unsuccessful. The server returned HTTP 403 Forbidden. Response body:
[b'{"ok":false,"error_code":403,"description":"Forbidden: bot was blocked by the user"}']

[LINE:417] # ERROR [2019-09-27 04:44:09,775]: A request to the Telegram API was unsuccessful. The server returned HTTP 403 Forbidden. Response body:
[b'{"ok":false,"error_code":403,"description":"Forbidden: bot was blocked by the user"}']
[LINE:652] # INFO [2019-09-27 04:44:09,777]: –î–º–∏—Ç—Ä–∏–π –ï—Ä–º–∞–∫–æ–≤ None üëç–Ω–∞–∑–∞–¥ –≤ –±—É–¥—É—â–µ–µ
[LINE:74] # INFO [2019-09-27 04:44:09,864]: New user @None
[LINE:735] # INFO [2019-09-27 04:44:09,865]: Starting new HTTPS connection (1): alarmerbot.ru
[LINE:74] # INFO [2019-09-27 04:44:10,057]: New user @doxadoxa
[LINE:735] # INFO [2019-09-27 04:44:10,060]: Starting new HTTPS connection (1): alarmerbot.ru
[LINE:74] # INFO [2019-09-27 04:44:10,475]: New user @themefiston
[LINE:735] # INFO [2019-09-27 04:44:10,478]: Starting new HTTPS connection (1): alarmerbot.ru
[LINE:652] # INFO [2019-09-27 04:44:10,520]: Alexandr Isaev üêà
[LINE:652] # INFO [2019-09-27 04:44:10,661]: Alexandr Isaev üëç
[LINE:652] # INFO [2019-09-27 04:44:10,824]: –î–∞–Ω–∏–∏–ª –ö–∞—Ä–ø–µ–Ω–∫–æ –ü–æ–¥–æ–±—Ä–∞—Ç—å —Ñ–∏–ª—å–ºüéû
[LINE:652] # INFO [2019-09-27 04:44:10,907]: –î–∞–Ω–∏–∏–ª –ö–∞—Ä–ø–µ–Ω–∫–æ –ü–æ–¥–æ–±—Ä–∞—Ç—å —Ñ–∏–ª—å–ºüéû
[LINE:265] # INFO [2019-09-27 04:44:11,018]: Predicting: 0:00:00.050934
[LINE:265] # INFO [2019-09-27 04:44:11,062]: Predicting: 0:00:00.034172
[LINE:652] # INFO [2019-09-27 04:44:11,853]: Petr Volnov üëé
[LINE:735] # INFO [2019-09-27 04:44:12,161]: Starting new HTTPS connection (1): api.telegram.org
[LINE:65] # ERROR [2019-09-27 04:44:12,564]: ApiException occurred, args=('A request to the Telegram API was unsuccessful. The server returned HTTP 409 Conflict. Response body:\n[b\'{"ok":false,"error_code":409,"description":"Conflict: terminated by other getUpdates request; make sure that only one bot instance is running"}\']',)
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/telebot/util.py", line 59, in run
    task(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/telebot/__init__.py", line 276, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1), timeout=timeout)
  File "/usr/local/lib/python3.5/dist-packages/telebot/__init__.py", line 246, in get_updates
    json_updates = apihelper.get_updates(self.token, offset, limit, timeout, allowed_updates)
  File "/usr/local/lib/python3.5/dist-packages/telebot/apihelper.py", line 180, in get_updates
    return _make_request(token, method_url, params=payload)
  File "/usr/local/lib/python3.5/dist-packages/telebot/apihelper.py", line 56, in _make_request
    return _check_result(method_name, result)['result']
  File "/usr/local/lib/python3.5/dist-packages/telebot/apihelper.py", line 75, in _check_result
    raise ApiException(msg, method_name, result)
telebot.apihelper.ApiException: A request to the Telegram API was unsuccessful. The server returned HTTP 409 Conflict. Response body:
[b'{"ok":false,"error_code":409,"description":"Conflict: terminated by other getUpdates request; make sure that only one bot instance is running"}']

[LINE:735] # INFO [2019-09-27 04:44:12,792]: Starting new HTTPS connection (1): api.telegram.org
[LINE:65] # ERROR [2019-09-27 04:44:16,191]: ApiException occurred, args=('A request to the Telegram API was unsuccessful. The server returned HTTP 409 Conflict. Response body:\n[b\'{"ok":false,"error_code":409,"description":"Conflict: terminated by other getUpdates request; make sure that only one bot instance is running"}\']',)
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/telebot/util.py", line 59, in run
    task(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/telebot/__init__.py", line 276, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1), timeout=timeout)
  File "/usr/local/lib/python3.5/dist-packages/telebot/__init__.py", line 246, in get_updates
    json_updates = apihelper.get_updates(self.token, offset, limit, timeout, allowed_updates)
  File "/usr/local/lib/python3.5/dist-packages/telebot/apihelper.py", line 180, in get_updates
    return _make_request(token, method_url, params=payload)
  File "/usr/local/lib/python3.5/dist-packages/telebot/apihelper.py", line 56, in _make_request
    return _check_result(method_name, result)['result']
  File "/usr/local/lib/python3.5/dist-packages/telebot/apihelper.py", line 75, in _check_result
    raise ApiException(msg, method_name, result)
telebot.apihelper.ApiException: A request to the Telegram API was unsuccessful. The server returned HTTP 409 Conflict. Response body:
[b'{"ok":false,"error_code":409,"description":"Conflict: terminated by other getUpdates request; make sure that only one bot instance is running"}']

[LINE:735] # INFO [2019-09-27 04:44:22,137]: Starting new HTTPS connection (1): api.telegram.org
[LINE:735] # INFO [2019-09-27 04:44:22,407]: Starting new HTTPS connection (1): api.telegram.org
[LINE:735] # INFO [2019-09-27 04:44:22,423]: Starting new HTTPS connection (1): api.telegram.org
[LINE:735] # INFO [2019-09-27 04:44:22,448]: Starting new HTTPS connection (1): api.telegram.org
[LINE:735] # INFO [2019-09-27 04:44:22,454]: Starting new HTTPS connection (1): api.telegram.org
[LINE:735] # INFO [2019-09-27 04:44:22,492]: Starting new HTTPS connection (1): api.telegram.org
[LINE:735] # INFO [2019-09-27 04:44:22,507]: Starting new HTTPS connection (1): api.telegram.org
[LINE:735] # INFO [2019-09-27 04:44:22,511]: Starting new HTTPS connection (1): api.telegram.org
[LINE:735] # INFO [2019-09-27 04:44:22,535]: Starting new HTTPS connection (1): api.telegram.org
[LINE:735] # INFO [2019-09-27 04:44:22,553]: Starting new HTTPS connection (1): api.telegram.org
[LINE:735] # INFO [2019-09-27 04:44:22,564]: Starting new HTTPS connection (1): api.telegram.org
[LINE:735] # INFO [2019-09-27 04:44:22,625]: Starting new HTTPS connection (1): api.telegram.org
[LINE:821] # INFO [2019-09-27 04:56:07,718]: Starting on server 2.1
[LINE:735] # INFO [2019-09-27 04:56:07,727]: Starting new HTTPS connection (1): api.telegram.org
[LINE:652] # INFO [2019-09-27 04:57:53,081]: Daniil Orekhov –ü–æ–Ω—Ä–∞–≤–∏–≤—à–∏–µ—Å—èüß°
[LINE:735] # INFO [2019-09-27 04:57:53,085]: Starting new HTTPS connection (1): api.telegram.org
[LINE:652] # INFO [2019-09-27 04:57:56,912]: Daniil Orekhov –ü–æ–¥–æ–±—Ä–∞—Ç—å —Ñ–∏–ª—å–ºüéû
[LINE:65] # ERROR [2019-09-27 04:57:57,319]: ValueError occurred, args=("'a' cannot be empty unless no samples are taken",)
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/telebot/util.py", line 59, in run
    task(*args, **kwargs)
  File "telsent.py", line 697, in repeat_all_messages
    u = next_films_collections(u)
  File "telsent.py", line 304, in next_films_collections
    u.predict_films += predict_film_list(u.tel_id)
  File "telsent.py", line 263, in predict_film_list
    pred = np.random.choice(list(predict.keys()), p=pb, size=20)
  File "mtrand.pyx", line 773, in numpy.random.mtrand.RandomState.choice
ValueError: 'a' cannot be empty unless no samples are taken

[LINE:831] # INFO [2019-09-27 04:57:57,319]: 'a' cannot be empty unless no samples are taken
[LINE:836] # INFO [2019-09-27 04:57:57,321]: <traceback object at 0x7f359c3e10c8>
[LINE:74] # INFO [2019-09-27 04:57:57,321]: 'a' cannot be empty unless no samples are taken
[LINE:735] # INFO [2019-09-27 04:57:57,323]: Starting new HTTPS connection (1): alarmerbot.ru
[LINE:831] # INFO [2019-09-27 04:57:57,759]: 'a' cannot be empty unless no samples are taken
[LINE:836] # INFO [2019-09-27 04:57:57,759]: <traceback object at 0x7f359c3ccf88>
[LINE:74] # INFO [2019-09-27 04:57:57,760]: 'a' cannot be empty unless no samples are taken
[LINE:735] # INFO [2019-09-27 04:57:57,761]: Starting new HTTPS connection (1): alarmerbot.ru
[LINE:735] # INFO [2019-09-27 04:57:57,762]: Starting new HTTPS connection (1): api.telegram.org
[LINE:831] # INFO [2019-09-27 04:57:58,216]: 'a' cannot be empty unless no samples are taken
[LINE:836] # INFO [2019-09-27 04:57:58,218]: <traceback object at 0x7f359c3e10c8>
[LINE:74] # INFO [2019-09-27 04:57:58,219]: 'a' cannot be empty unless no samples are taken
[LINE:735] # INFO [2019-09-27 04:57:58,223]: Starting new HTTPS connection (1): alarmerbot.ru
[LINE:735] # INFO [2019-09-27 04:57:58,226]: Starting new HTTPS connection (1): api.telegram.org
[LINE:65] # ERROR [2019-09-27 04:57:58,336]: ApiException occurred, args=('A request to the Telegram API was unsuccessful. The server returned HTTP 409 Conflict. Response body:\n[b\'{"ok":false,"error_code":409,"description":"Conflict: terminated by other getUpdates request; make sure that only one bot instance is running"}\']',)
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/telebot/util.py", line 59, in run
    task(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/telebot/__init__.py", line 276, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1), timeout=timeout)
  File "/usr/local/lib/python3.5/dist-packages/telebot/__init__.py", line 246, in get_updates
    json_updates = apihelper.get_updates(self.token, offset, limit, timeout, allowed_updates)
  File "/usr/local/lib/python3.5/dist-packages/telebot/apihelper.py", line 180, in get_updates
    return _make_request(token, method_url, params=payload)
  File "/usr/local/lib/python3.5/dist-packages/telebot/apihelper.py", line 56, in _make_request
    return _check_result(method_name, result)['result']
  File "/usr/local/lib/python3.5/dist-packages/telebot/apihelper.py", line 75, in _check_result
    raise ApiException(msg, method_name, result)
telebot.apihelper.ApiException: A request to the Telegram API was unsuccessful. The server returned HTTP 409 Conflict. Response body:
[b'{"ok":false,"error_code":409,"description":"Conflict: terminated by other getUpdates request; make sure that only one bot instance is running"}']

[LINE:831] # INFO [2019-09-27 04:57:58,659]: 'a' cannot be empty unless no samples are taken
[LINE:836] # INFO [2019-09-27 04:57:58,660]: <traceback object at 0x7f359c3ccf88>
[LINE:74] # INFO [2019-09-27 04:57:58,661]: 'a' cannot be empty unless no samples are taken
[LINE:735] # INFO [2019-09-27 04:57:58,663]: Starting new HTTPS connection (1): alarmerbot.ru
[LINE:735] # INFO [2019-09-27 04:57:58,665]: Starting new HTTPS connection (1): api.telegram.org
[LINE:831] # INFO [2019-09-27 04:57:59,111]: 'a' cannot be empty unless no samples are taken
[LINE:836] # INFO [2019-09-27 04:57:59,112]: <traceback object at 0x7f359c3e10c8>
[LINE:74] # INFO [2019-09-27 04:57:59,113]: 'a' cannot be empty unless no samples are taken
[LINE:735] # INFO [2019-09-27 04:57:59,115]: Starting new HTTPS connection (1): alarmerbot.ru
[LINE:735] # INFO [2019-09-27 04:57:59,117]: Starting new HTTPS connection (1): api.telegram.org
[LINE:832] # INFO [2019-09-27 04:58:38,446]: Starting on server 2.1
[LINE:735] # INFO [2019-09-27 04:58:38,456]: Starting new HTTPS connection (1): api.telegram.org
[LINE:65] # ERROR [2019-09-27 04:59:19,446]: NameError occurred, args=("name 'HELP_TEXT' is not defined",)
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/telebot/util.py", line 59, in run
    task(*args, **kwargs)
  File "telsent.py", line 348, in menu
    bot.send_message(message.chat.id, HELP_TEXT)
NameError: name 'HELP_TEXT' is not defined

[LINE:842] # INFO [2019-09-27 04:59:19,446]: name 'HELP_TEXT' is not defined
[LINE:847] # INFO [2019-09-27 04:59:19,447]: <traceback object at 0x7f515c20eac8>
[LINE:74] # INFO [2019-09-27 04:59:19,448]: name 'HELP_TEXT' is not defined
[LINE:735] # INFO [2019-09-27 04:59:19,449]: Starting new HTTPS connection (1): alarmerbot.ru
[LINE:842] # INFO [2019-09-27 04:59:19,854]: name 'HELP_TEXT' is not defined
[LINE:847] # INFO [2019-09-27 04:59:19,855]: <traceback object at 0x7f515c20e9c8>
[LINE:74] # INFO [2019-09-27 04:59:19,856]: name 'HELP_TEXT' is not defined
[LINE:735] # INFO [2019-09-27 04:59:19,859]: Starting new HTTPS connection (1): alarmerbot.ru
[LINE:735] # INFO [2019-09-27 04:59:19,861]: Starting new HTTPS connection (1): api.telegram.org
[LINE:65] # ERROR [2019-09-27 04:59:20,250]: ApiException occurred, args=('A request to the Telegram API was unsuccessful. The server returned HTTP 409 Conflict. Response body:\n[b\'{"ok":false,"error_code":409,"description":"Conflict: terminated by other getUpdates request; make sure that only one bot instance is running"}\']',)
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/telebot/util.py", line 59, in run
    task(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/telebot/__init__.py", line 276, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1), timeout=timeout)
  File "/usr/local/lib/python3.5/dist-packages/telebot/__init__.py", line 246, in get_updates
    json_updates = apihelper.get_updates(self.token, offset, limit, timeout, allowed_updates)
  File "/usr/local/lib/python3.5/dist-packages/telebot/apihelper.py", line 180, in get_updates
    return _make_request(token, method_url, params=payload)
  File "/usr/local/lib/python3.5/dist-packages/telebot/apihelper.py", line 56, in _make_request
    return _check_result(method_name, result)['result']
  File "/usr/local/lib/python3.5/dist-packages/telebot/apihelper.py", line 75, in _check_result
    raise ApiException(msg, method_name, result)
telebot.apihelper.ApiException: A request to the Telegram API was unsuccessful. The server returned HTTP 409 Conflict. Response body:
[b'{"ok":false,"error_code":409,"description":"Conflict: terminated by other getUpdates request; make sure that only one bot instance is running"}']

[LINE:842] # INFO [2019-09-27 04:59:20,283]: name 'HELP_TEXT' is not defined
[LINE:847] # INFO [2019-09-27 04:59:20,284]: <traceback object at 0x7f515c20eac8>
[LINE:74] # INFO [2019-09-27 04:59:20,284]: name 'HELP_TEXT' is not defined
[LINE:735] # INFO [2019-09-27 04:59:20,285]: Starting new HTTPS connection (1): alarmerbot.ru
[LINE:735] # INFO [2019-09-27 04:59:20,287]: Starting new HTTPS connection (1): api.telegram.org
[LINE:842] # INFO [2019-09-27 04:59:20,727]: name 'HELP_TEXT' is not defined
[LINE:847] # INFO [2019-09-27 04:59:20,729]: <traceback object at 0x7f515c20e9c8>
[LINE:74] # INFO [2019-09-27 04:59:20,729]: name 'HELP_TEXT' is not defined
[LINE:735] # INFO [2019-09-27 04:59:20,732]: Starting new HTTPS connection (1): alarmerbot.ru
[LINE:735] # INFO [2019-09-27 04:59:20,733]: Starting new HTTPS connection (1): api.telegram.org
[LINE:842] # INFO [2019-09-27 04:59:21,136]: name 'HELP_TEXT' is not defined
[LINE:847] # INFO [2019-09-27 04:59:21,138]: <traceback object at 0x7f515c20eac8>
[LINE:74] # INFO [2019-09-27 04:59:21,138]: name 'HELP_TEXT' is not defined
[LINE:735] # INFO [2019-09-27 04:59:21,141]: Starting new HTTPS connection (1): alarmerbot.ru
[LINE:735] # INFO [2019-09-27 04:59:21,144]: Starting new HTTPS connection (1): api.telegram.org
[LINE:832] # INFO [2019-09-27 04:59:48,804]: Starting on server 2.1
[LINE:735] # INFO [2019-09-27 04:59:48,814]: Starting new HTTPS connection (1): api.telegram.org
[LINE:735] # INFO [2019-09-27 05:00:13,528]: Starting new HTTPS connection (1): api.telegram.org
[LINE:660] # INFO [2019-09-27 05:00:22,695]: Petr Volnov –í—Å–µ —Ö–æ—Ä–æ—à–æ
[LINE:74] # INFO [2019-09-27 05:00:22,695]: Petr Volnov need help: –í—Å–µ —Ö–æ—Ä–æ—à–æ
[LINE:735] # INFO [2019-09-27 05:00:22,697]: Starting new HTTPS connection (1): alarmerbot.ru
[LINE:735] # INFO [2019-09-27 05:00:23,121]: Starting new HTTPS connection (1): api.telegram.org
[LINE:839] # INFO [2019-09-27 05:09:35,657]: Starting on server 2.1
[LINE:735] # INFO [2019-09-27 05:09:35,672]: Starting new HTTPS connection (1): api.telegram.org
[LINE:664] # INFO [2019-09-27 05:10:10,454]: Petr Volnov –í—Å–µ —Ö–ª–æ—Ä–æ—à–æ
[LINE:74] # INFO [2019-09-27 05:10:10,454]: Petr Volnov need help: –í—Å–µ —Ö–ª–æ—Ä–æ—à–æ
[LINE:735] # INFO [2019-09-27 05:10:10,455]: Starting new HTTPS connection (1): alarmerbot.ru
[LINE:735] # INFO [2019-09-27 05:10:10,884]: Starting new HTTPS connection (1): api.telegram.org
[LINE:664] # INFO [2019-09-27 05:10:22,812]: Petr Volnov –ü–æ–¥–æ–±—Ä–∞—Ç—å —Ñ–∏–ª—å–ºüéû
[LINE:664] # INFO [2019-09-27 05:10:28,037]: Petr Volnov üëÅ
[LINE:735] # INFO [2019-09-27 05:10:28,045]: Starting new HTTPS connection (1): api.telegram.org
[LINE:664] # INFO [2019-09-27 05:10:30,504]: Petr Volnov üëÅ
[LINE:664] # INFO [2019-09-27 05:10:36,947]: Petr Volnov üëç
[LINE:664] # INFO [2019-09-27 05:10:41,161]: Petr Volnov üëÅ
[LINE:664] # INFO [2019-09-27 05:10:45,016]: Petr Volnov üëÅ
[LINE:664] # INFO [2019-09-27 05:10:46,887]: Petr Volnov üëÅ
[LINE:664] # INFO [2019-09-27 05:10:49,219]: Petr Volnov üëÅ
[LINE:664] # INFO [2019-09-27 05:10:54,160]: Petr Volnov üí©
[LINE:664] # INFO [2019-09-27 05:11:02,907]: Petr Volnov üëÅ
[LINE:664] # INFO [2019-09-27 05:11:08,024]: Petr Volnov üëé
[LINE:664] # INFO [2019-09-27 05:11:13,411]: Petr Volnov üëÅ
[LINE:664] # INFO [2019-09-27 05:11:15,794]: Petr Volnov üëÅ
[LINE:664] # INFO [2019-09-27 05:11:22,361]: Petr Volnov üëé
[LINE:664] # INFO [2019-09-27 05:11:52,962]: Petr Volnov üëé
[LINE:114] # ERROR [2019-09-27 05:11:53,059]: Can't edit message
[LINE:114] # ERROR [2019-09-27 05:11:54,032]: Can't edit message
[LINE:444] # INFO [2019-09-27 05:12:08,670]: neafiol: more_7099
[LINE:664] # INFO [2019-09-27 05:12:26,111]: Petr Volnov üëé
[LINE:664] # INFO [2019-09-27 05:12:52,738]: Petr Volnov üëÅ
[LINE:264] # INFO [2019-09-27 05:12:53,232]: Predicting: 0:00:00.044489
[LINE:664] # INFO [2019-09-27 05:12:58,206]: Petr Volnov üëé
[LINE:664] # INFO [2019-09-27 05:13:19,075]: Petr Volnov üëÅ
[LINE:849] # INFO [2019-09-27 05:20:37,571]: Starting on server 2.1
[LINE:735] # INFO [2019-09-27 05:20:37,584]: Starting new HTTPS connection (1): api.telegram.org
[LINE:674] # INFO [2019-09-27 05:20:44,232]: Petr Volnov üí©
[LINE:735] # INFO [2019-09-27 05:20:44,239]: Starting new HTTPS connection (1): api.telegram.org
[LINE:674] # INFO [2019-09-27 05:20:49,936]: Petr Volnov üí©
[LINE:674] # INFO [2019-09-27 05:20:52,980]: Petr Volnov üëÅ
[LINE:735] # INFO [2019-09-27 05:20:52,990]: Starting new HTTPS connection (1): api.telegram.org
[LINE:674] # INFO [2019-09-27 05:21:00,530]: Petr Volnov üëç
[LINE:674] # INFO [2019-09-27 05:24:40,078]: –î–∞–Ω–∏–∏–ª –ö–∞—Ä–ø–µ–Ω–∫–æ üëé
[LINE:674] # INFO [2019-09-27 05:24:48,650]: –î–∞–Ω–∏–∏–ª –ö–∞—Ä–ø–µ–Ω–∫–æ üëé
[LINE:674] # INFO [2019-09-27 05:24:52,438]: –î–∞–Ω–∏–∏–ª –ö–∞—Ä–ø–µ–Ω–∫–æ üëÅ
[LINE:674] # INFO [2019-09-27 05:24:55,537]: –î–∞–Ω–∏–∏–ª –ö–∞—Ä–ø–µ–Ω–∫–æ üëç
[LINE:674] # INFO [2019-09-27 05:25:00,269]: –î–∞–Ω–∏–∏–ª –ö–∞—Ä–ø–µ–Ω–∫–æ üëÅ
[LINE:674] # INFO [2019-09-27 05:26:07,983]: –î–∞–Ω–∏–∏–ª –ö–∞—Ä–ø–µ–Ω–∫–æ üëé
[LINE:674] # INFO [2019-09-27 05:26:12,423]: –î–∞–Ω–∏–∏–ª –ö–∞—Ä–ø–µ–Ω–∫–æ üëç
[LINE:674] # INFO [2019-09-27 05:26:18,320]: –î–∞–Ω–∏–∏–ª –ö–∞—Ä–ø–µ–Ω–∫–æ üí©
[LINE:674] # INFO [2019-09-27 05:27:03,197]: –î–∞–Ω–∏–∏–ª –ö–∞—Ä–ø–µ–Ω–∫–æ üëé
[LINE:115] # ERROR [2019-09-27 05:27:03,422]: Can't edit message
[LINE:115] # ERROR [2019-09-27 05:27:04,249]: Can't edit message
[LINE:674] # INFO [2019-09-27 05:27:09,916]: –î–∞–Ω–∏–∏–ª –ö–∞—Ä–ø–µ–Ω–∫–æ üëé
[LINE:674] # INFO [2019-09-27 05:27:12,154]: –î–∞–Ω–∏–∏–ª –ö–∞—Ä–ø–µ–Ω–∫–æ üëÅ
[LINE:674] # INFO [2019-09-27 05:27:16,532]: –î–∞–Ω–∏–∏–ª –ö–∞—Ä–ø–µ–Ω–∫–æ üëç
[LINE:674] # INFO [2019-09-27 05:27:20,538]: –î–∞–Ω–∏–∏–ª –ö–∞—Ä–ø–µ–Ω–∫–æ üëé
[LINE:674] # INFO [2019-09-27 05:27:22,957]: –î–∞–Ω–∏–∏–ª –ö–∞—Ä–ø–µ–Ω–∫–æ üëé
[LINE:674] # INFO [2019-09-27 05:27:34,023]: –î–∞–Ω–∏–∏–ª –ö–∞—Ä–ø–µ–Ω–∫–æ üëé
[LINE:265] # INFO [2019-09-27 05:27:35,064]: Predicting: 0:00:00.040110
[LINE:674] # INFO [2019-09-27 05:27:36,698]: –î–∞–Ω–∏–∏–ª –ö–∞—Ä–ø–µ–Ω–∫–æ üëÅ
[LINE:674] # INFO [2019-09-27 05:27:40,032]: –î–∞–Ω–∏–∏–ª –ö–∞—Ä–ø–µ–Ω–∫–æ üëé
[LINE:674] # INFO [2019-09-27 05:27:45,365]: –î–∞–Ω–∏–∏–ª –ö–∞—Ä–ø–µ–Ω–∫–æ üëé
[LINE:674] # INFO [2019-09-27 05:27:48,799]: –î–∞–Ω–∏–∏–ª –ö–∞—Ä–ø–µ–Ω–∫–æ üëé
[LINE:674] # INFO [2019-09-27 05:28:02,716]: –î–∞–Ω–∏–∏–ª –ö–∞—Ä–ø–µ–Ω–∫–æ üëç
[LINE:674] # INFO [2019-09-27 05:28:08,131]: –î–∞–Ω–∏–∏–ª –ö–∞—Ä–ø–µ–Ω–∫–æ üëé
[LINE:674] # INFO [2019-09-27 05:28:18,667]: –î–∞–Ω–∏–∏–ª –ö–∞—Ä–ø–µ–Ω–∫–æ üëÅ
[LINE:674] # INFO [2019-09-27 05:28:37,229]: –î–∞–Ω–∏–∏–ª –ö–∞—Ä–ø–µ–Ω–∫–æ üëé
[LINE:674] # INFO [2019-09-27 05:28:40,982]: –î–∞–Ω–∏–∏–ª –ö–∞—Ä–ø–µ–Ω–∫–æ üëé
[LINE:674] # INFO [2019-09-27 05:31:01,001]: Petr Volnov –£ –º–µ–Ω—è –Ω–µ —Ä–∞–±–æ—Ç–∞–µ—Ç –ø–æ–¥–±–æ—Ä–∫–∞ —Ñ–∏–ª—å–º–æ–≤
[LINE:74] # INFO [2019-09-27 05:31:01,002]: Petr Volnov need help: –£ –º–µ–Ω—è –Ω–µ —Ä–∞–±–æ—Ç–∞–µ—Ç –ø–æ–¥–±–æ—Ä–∫–∞ —Ñ–∏–ª—å–º–æ–≤
[LINE:735] # INFO [2019-09-27 05:31:01,005]: Starting new HTTPS connection (1): alarmerbot.ru
[LINE:851] # INFO [2019-09-27 05:44:14,756]: Starting on server 2.1
[LINE:735] # INFO [2019-09-27 05:44:14,766]: Starting new HTTPS connection (1): api.telegram.org
[LINE:735] # INFO [2019-09-27 05:44:28,665]: Starting new HTTPS connection (1): api.telegram.org
[LINE:674] # INFO [2019-09-27 05:44:32,731]: Petr Volnov test
[LINE:74] # INFO [2019-09-27 05:44:32,731]: Petr Volnov need help: test
[LINE:735] # INFO [2019-09-27 05:44:32,733]: Starting new HTTPS connection (1): alarmerbot.ru
[LINE:735] # INFO [2019-09-27 05:44:33,294]: Starting new HTTPS connection (1): api.telegram.org
[LINE:454] # INFO [2019-09-27 05:45:48,318]: None: info_sex_0
[LINE:674] # INFO [2019-09-27 05:45:58,607]: . None –ü
[LINE:674] # INFO [2019-09-27 05:46:04,464]: . None 1
[LINE:674] # INFO [2019-09-27 05:46:09,953]: . None –ü–æ–¥–æ–±—Ä–∞—Ç—å —Ñ–∏–ª—å–ºüéû
[LINE:265] # INFO [2019-09-27 05:46:10,644]: Predicting: 0:00:00.069999
[LINE:454] # INFO [2019-09-27 05:53:13,700]: doxadoxa: info_sex_0
[LINE:674] # INFO [2019-09-27 05:53:20,246]: Taras D 25
[LINE:674] # INFO [2019-09-27 05:53:22,390]: Taras D –ü–æ–¥–æ–±—Ä–∞—Ç—å —Ñ–∏–ª—å–ºüéû
[LINE:265] # INFO [2019-09-27 05:53:22,600]: Predicting: 0:00:00.077936
[LINE:356] # INFO [2019-09-27 05:53:32,059]: like like_-1
[LINE:265] # INFO [2019-09-27 05:53:32,126]: Predicting: 0:00:00.049360
[LINE:162] # INFO [2019-09-27 05:53:32,346]: Cant edit list of films
[LINE:265] # INFO [2019-09-27 05:53:32,538]: Predicting: 0:00:00.039221
[LINE:162] # INFO [2019-09-27 05:53:32,680]: Cant edit list of films
[LINE:265] # INFO [2019-09-27 05:53:32,908]: Predicting: 0:00:00.059185
[LINE:162] # INFO [2019-09-27 05:53:33,076]: Cant edit list of films
[LINE:265] # INFO [2019-09-27 05:53:33,344]: Predicting: 0:00:00.038421
[LINE:162] # INFO [2019-09-27 05:53:33,542]: Cant edit list of films
[LINE:265] # INFO [2019-09-27 05:53:33,731]: Predicting: 0:00:00.034423
[LINE:162] # INFO [2019-09-27 05:53:33,849]: Cant edit list of films
[LINE:356] # INFO [2019-09-27 05:53:36,687]: like like_-1
[LINE:65] # ERROR [2019-09-27 05:53:36,865]: ValueError occurred, args=("'a' cannot be empty unless no samples are taken",)
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/telebot/util.py", line 59, in run
    task(*args, **kwargs)
  File "telsent.py", line 385, in likefilm
    u = next_films_collections(u)
  File "telsent.py", line 304, in next_films_collections
    u.predict_films += predict_film_list(u.tel_id)
  File "telsent.py", line 263, in predict_film_list
    pred = np.random.choice(list(predict.keys()), p=pb, size=20)
  File "mtrand.pyx", line 773, in numpy.random.mtrand.RandomState.choice
ValueError: 'a' cannot be empty unless no samples are taken

[LINE:861] # INFO [2019-09-27 05:53:36,866]: 'a' cannot be empty unless no samples are taken
[LINE:866] # INFO [2019-09-27 05:53:36,868]: <traceback object at 0x7fdfd60bba88>
[LINE:74] # INFO [2019-09-27 05:53:36,868]: 'a' cannot be empty unless no samples are taken
[LINE:735] # INFO [2019-09-27 05:53:36,870]: Starting new HTTPS connection (1): alarmerbot.ru
[LINE:861] # INFO [2019-09-27 05:53:37,316]: 'a' cannot be empty unless no samples are taken
[LINE:866] # INFO [2019-09-27 05:53:37,317]: <traceback object at 0x7fdfd60bb988>
[LINE:74] # INFO [2019-09-27 05:53:37,317]: 'a' cannot be empty unless no samples are taken
[LINE:735] # INFO [2019-09-27 05:53:37,318]: Starting new HTTPS connection (1): alarmerbot.ru
[LINE:735] # INFO [2019-09-27 05:53:37,319]: Starting new HTTPS connection (1): api.telegram.org
[LINE:65] # ERROR [2019-09-27 05:53:37,742]: ApiException occurred, args=('A request to the Telegram API was unsuccessful. The server returned HTTP 409 Conflict. Response body:\n[b\'{"ok":false,"error_code":409,"description":"Conflict: terminated by other getUpdates request; make sure that only one bot instance is running"}\']',)
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/telebot/util.py", line 59, in run
    task(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/telebot/__init__.py", line 276, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1), timeout=timeout)
  File "/usr/local/lib/python3.5/dist-packages/telebot/__init__.py", line 246, in get_updates
    json_updates = apihelper.get_updates(self.token, offset, limit, timeout, allowed_updates)
  File "/usr/local/lib/python3.5/dist-packages/telebot/apihelper.py", line 180, in get_updates
    return _make_request(token, method_url, params=payload)
  File "/usr/local/lib/python3.5/dist-packages/telebot/apihelper.py", line 56, in _make_request
    return _check_result(method_name, result)['result']
  File "/usr/local/lib/python3.5/dist-packages/telebot/apihelper.py", line 75, in _check_result
    raise ApiException(msg, method_name, result)
telebot.apihelper.ApiException: A request to the Telegram API was unsuccessful. The server returned HTTP 409 Conflict. Response body:
[b'{"ok":false,"error_code":409,"description":"Conflict: terminated by other getUpdates request; make sure that only one bot instance is running"}']

[LINE:861] # INFO [2019-09-27 05:53:37,749]: 'a' cannot be empty unless no samples are taken
[LINE:866] # INFO [2019-09-27 05:53:37,750]: <traceback object at 0x7fdfd60bba88>
[LINE:74] # INFO [2019-09-27 05:53:37,750]: 'a' cannot be empty unless no samples are taken
[LINE:735] # INFO [2019-09-27 05:53:37,752]: Starting new HTTPS connection (1): alarmerbot.ru
[LINE:735] # INFO [2019-09-27 05:53:37,753]: Starting new HTTPS connection (1): api.telegram.org
[LINE:861] # INFO [2019-09-27 05:53:38,171]: 'a' cannot be empty unless no samples are taken
[LINE:866] # INFO [2019-09-27 05:53:38,173]: <traceback object at 0x7fdfd60bb988>
[LINE:74] # INFO [2019-09-27 05:53:38,173]: 'a' cannot be empty unless no samples are taken
[LINE:735] # INFO [2019-09-27 05:53:38,175]: Starting new HTTPS connection (1): alarmerbot.ru
[LINE:735] # INFO [2019-09-27 05:53:38,177]: Starting new HTTPS connection (1): api.telegram.org
[LINE:861] # INFO [2019-09-27 05:53:38,596]: 'a' cannot be empty unless no samples are taken
[LINE:866] # INFO [2019-09-27 05:53:38,598]: <traceback object at 0x7fdfd60bba88>
[LINE:74] # INFO [2019-09-27 05:53:38,599]: 'a' cannot be empty unless no samples are taken
[LINE:735] # INFO [2019-09-27 05:53:38,602]: Starting new HTTPS connection (1): alarmerbot.ru
[LINE:735] # INFO [2019-09-27 05:53:38,604]: Starting new HTTPS connection (1): api.telegram.org
[LINE:851] # INFO [2019-09-27 05:54:34,775]: Starting on server 2.1
[LINE:735] # INFO [2019-09-27 05:54:34,785]: Starting new HTTPS connection (1): api.telegram.org
